### ISSUE TITLE
How to hide security fields in gocd secret page

### ISSUE THREAD

**Issue by klinux** [gocd-contrib/secrets-skeleton-plugin#1]
Hi,

I implement the secrets plugin to hashicorp vault, but, when I show configs in the secret pages settings, the token is in plain text, but I want that setting feel like kubernetes plugin page, where token is masked with *****, there some way to replicate this result?

Thank you

**Comment by varshavaradarajan** [comment]
@klinux - there is already a vault plugin: https://github.com/gocd/gocd-vault-secret-plugin

@maheshp - any reason why its not listed in gocd.org/plugins?

**Comment by arvindsv** [comment]
Also, this is how that plugin makes those fields secure: https://github.com/gocd/gocd-vault-secret-plugin/blob/53b67f0233e3e9b0034bf9ece63935f55a9230ab/src/main/java/com/thoughtworks/gocd/secretmanager/vault/models/SecretConfig.java#L70

**Comment by klinux** [comment]
@varshavaradarajan thank you for this answer, yes, we develop our plugin because we didn't know about this plugin.

@arvindsv thank you, this is what I want to know, but we will use the official plugin.

**Comment by maheshp** [comment]
We have cut a stable release of the Vault Secrets Plugin - https://github.com/gocd/gocd-vault-secret-plugin/releases/tag/v1.0.0-23

The same has been listed on https://www.gocd.org/plugins/#secrets
